export const USER_CREATED = 0;
export const MESSAGE_ADDED = 1;
export const STATUS_CHANGED = 2;
export const PROGRESS_CHANGED = 3;
export const PROGRESS_DONE = 4;
export const PROGRESS_FAIL = 5;

export const GET_MSG_FROM_DB = 6;
export const RESET_BY_NAME = 7;
export const USER_DELETED = 8;
export const DELETE_DB = 9;

export const UPLOAD_MEDIA_MSG_ADDED = 50;
export const UPLOAD_MEDIA_USER_CREATED = 51;
export const UPLOAD_MEDIA_USER_DELETED = 52;
export const UPLOAD_MEDIA_PROGRESS_CHANGED = 53;
export const UPLOAD_MEDIA_PROGRESS_DONE = 54;
export const UPLOAD_MEDIA_PROGRESS_FAIL = 55;
export const UPLOAD_MEDIA_STATUS_CHANGED = 56;

export const UPLOAD_MEDIA_GET_MSG_FROM_DB = 57;
export const UPLOAD_MEDIA_RESET_BY_NAME = 58;
export const UPLOAD_MEDIA_DELETE_DB = 59;
export const UPLOAD_DELETE_BY_KEY_VALUE = 60;
export const OLD_UPLOAD_DELETE_BY_KEY_VALUE = 61;

export const DOWNLOAD_MEDIA_MSG_ADDED = 99;
export const DOWNLOAD_MEDIA_USER_CREATED = 98;
export const DOWNLOAD_MEDIA_USER_DELETED = 97;
export const DOWNLOAD_MEDIA_PROGRESS_CHANGED = 96;
export const DOWNLOAD_MEDIA_PROGRESS_DONE = 95;
export const DOWNLOAD_MEDIA_PROGRESS_FAIL = 94;
export const DOWNLOAD_MEDIA_STATUS_CHANGED = 93;
export const DOWNLOAD_ADD_DOWNLOAD_DIR = 92;
export const DOWNLOAD_DELETE_BY_KEY_VALUE = 91;
export const OLD_DOWNLOAD_DELETE_BY_KEY_VALUE = 90;

export const DOWNLOAD_MEDIA_GET_MSG_FROM_DB = 91;
export const DOWNLOAD_MEDIA_RESET_BY_NAME = 90;
export const DOWNLOAD_MEDIA_DELETE_DB = 89;
