export const USER_CREATED = 'USER_CREATED';
export const MESSAGE_ADDED = 'MESSAGE_ADDED';
export const STATUS_CHANGED = 'STATUS_CHANGED';
export const PROGRESS_CHANGED = 'PROGRESS_CHANGED';
export const PROGRESS_DONE = 'PROGRESS_DONE';
export const PROGRESS_FAIL = 'PROGRESS_FAIL';
